oe_content_event_person_reference.oe_event_speaker_type.*:
  type: config_entity
  label: 'Event speaker type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
