oe_content_persistent.settings:
  type: config_object
  label: 'Configuration for PURL.'
  mapping:
    base_url:
      type: uri
      label: 'Inter institutional base path'
    supported_entity_types:
      type: sequence
      label: 'Supported entity types'
      sequence:
        type: string
        label: 'Entity type ID'

linkit.matcher.entity:media:
  type: linkit.matcher.entity
  mapping:
    include_unpublished:
      type: boolean
    thumbnail:
      type: mapping
      mapping:
        show_thumbnail:
          type: boolean
        thumbnail_image_style:
          type: string
          nullable: true
