field.formatter.settings.timeline_formatter:
  type: mapping
  label: 'Timeline field formatter settings'
  mapping:
    limit:
      type: string
      label: 'Timeline item limit'
    show_more:
      type: label
      label: 'Show more button label'

field.value.timeline_field:
  type: mapping
  label: 'Default value'
  mapping:
    label:
      type: label
      label: 'Timeline item label'
    title:
      type: label
      label: 'Timeline item title'
    body:
      type: text
      label: 'Timeline item body'
    format:
      type: string
      label: 'Timeline item body format'
